config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users
  resources :rooms

  resources :hotels

   root 'home#index'

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
has_many :rooms, dependent: :destroy
validates :name, presence: true

accepts_nested_attributes_for :rooms, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true

def to_s
	name
end


end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :hotel

 validates :name, presence: true

	def to_s
	     name
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]

  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
    @hotel.rooms.build
  end

  # GET /hotels/1/edit
  def edit
    @hotel.rooms.build
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: 'Hotel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_params
      params.require(:hotel).permit(:name, rooms_attributes:[:id, :name, :_destroy])
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :hotel_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/home/index.html.erb
<h1>Bienvendo a travel-hotel</h1>

<% if user_signed_in? %>
	<p> Bienvenido <%= current_user.email %></p>
	<p> <%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete %></p>
<% else %>
	<p> <%= link_to "crear cuenta", new_user_registration_path %></p>
	<p>Si ya tienes cuenta:<%= link_to "logueate", new_user_session_path %> </p>
	<% end %>

<p></p>

app/views/hotels/_form.html.erb
<%= form_for(@hotel) do |f| %>
  <% if @hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
      <% @hotel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name  %><br>
    <%= f.text_field :name,  class:'form-control' %>
  </div>

  <h2>Rooms</h2>

<%= f.fields_for :rooms do |room| %>
<div class="room">
  <div class="field form-group">
    <%= room.label :name %> <br>
    <%= room.text_field :name, class:'form-control'%> <br>
    <div class="checkbox-inline">
    <%= room.check_box :_destroy %>
    <%= room.label :_destroy, 'Eliminar' %>
    </div>

  </div>


</div>

<%end%>


  <div class="actions">
    <%= f.submit class: 'btn btn-default' %>
  </div>
<% end %>

app/views/hotels/edit.html.erb
<h1>Editing Hotel</h1>

<%= render 'form' %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

app/views/hotels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hotels</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= hotel.name %></td>
        <td><%= link_to 'Show', hotel , class: 'btn btn-success' %></td>
        <td><%= link_to 'Edit', edit_hotel_path(hotel) , class: 'btn btn-default' %></td>
        <td><%= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Esta Segurp' } , class: 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to  new_hotel_path, class: 'btn btn-default' do %>
  <i class="glyphicon glyphicon-plus"></i> Nuevo Hotel
<% end %>

app/views/hotels/new.html.erb
<h1>New Hotel</h1>

<%= render 'form' %>

<%= link_to hotels_path ,class: 'btn btn-default' do %>
  <i class="glyphicon glyphicon-arrow-left"></i> Regresar
<% end %>

app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hotel.name %>
</p>

<h2>Room categoria</h2>
<% if @hotel.rooms.any? %>
<ul> 
<% @hotel.rooms.each do |room|%>
<li> <%=link_to room, room %></li>
<% end %>
</ul>
<% else %>
<p>no available</p>
<% end %>


<%= link_to 'Edit', edit_hotel_path(@hotel) %> |
<%= link_to 'Back', hotels_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'share/navigation' %>

<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>


<div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-3">
          <h3>Fastidio hotel</h3>
          <ul>
          <li><%= link_to hotels_path ,class: 'btn btn-default' do %>
  <i class="glyphicon glyphicon-equalizer"></i> Hotel
<% end %></li>
<li></li>
          <li><%= link_to rooms_path ,class: 'btn btn-default' do %>
  <i class="glyphicon glyphicon-bed"></i> Rooms
<% end %></li>
          <li></li>
          </ul>
        </div>
        <div class="col-xs-9">

          <%= yield %>

		</div>
	</div>
</div>


</body>
</html>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control'%>
  </div>
  <div class="field form-group">
    <%= f.label :hotel_id %><br>
    <%= f.text_field :hotel_id, class: 'form-control'%>
  </div>
  <div class="actions">
    <%= f.submit "Crear ", class: 'btn btn-default'  %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form' %>

<%= link_to  rooms_path, class: 'btn btn-default' do %>
  <i class="glyphicon glyphicon-arrow-left"></i> Regresar
<% end %> | <%= link_to  @room, class: 'btn btn-default' do %>
  <i class="glyphicon glyphicon-th-list"></i> Mostrar
<% end %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rooms</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Hotel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.hotel %></td>
        <td><%= link_to 'Show', room , class: 'btn btn-success'%></td>
        <td><%= link_to 'Edit', edit_room_path(room), class: 'btn btn-default' %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger btn-xs'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to  new_room_path, class: 'btn btn-default' do %>
  <i class="glyphicon glyphicon-plus"></i> Nuevo Room
<% end %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form' %>

<%= link_to  rooms_path, class: 'btn btn-default' do %>
  <i class="glyphicon glyphicon-arrow-left"></i> Regresar
<% end %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>Hotel:</strong>
  <%= @room.hotel %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

app/views/share/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Prueba Hotel</a>
    </div>  


<!--
    <div>

<% if user_signed_in? %>
<ul class="nav nav-pills">
  <li role="presentation" class="active">Bienvenido <%= current_user.email %></li>
  <li role="presentation"><%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete %></li>  
</ul>
<% else %>
<ul class="nav nav-pills">
  <li role="presentation" class="active"><%= link_to "crear cuenta", new_user_registration_path %></li>
  <li role="presentation"><%= link_to "logueate", new_user_session_path %></li>  
</ul>


	<% end %>

</div>
-->
<div>
	<% if user_signed_in? %>

  <p class="navbar-text navbar-right">Bienvenido <%= current_user.email %></p>
  <button type="button" class="btn btn-default navbar-btn navbar-right"><%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete %></button>  

	<% else %>

	<button type="button" class="btn btn-default navbar-btn"><%= link_to "crear cuenta", new_user_registration_path %></button>
  	<button type="button" class="btn btn-default navbar-btn"><%= link_to "logueate", new_user_session_path %></button> 


	<% end %>
</div>

    
  </div>
</nav>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>